export const POST_CREATE_PENDING = 'POST_CREATE_PENDING';
export const POST_INFO = 'POST_INFO';
export const POST_CREATE = 'POST_CREATE';
export const POST_UPDATE = 'POST_UPDATE';

export const POST_VERIFICATION_PENDING = 'POST_VERIFICATION_PENDING';
export const GET_POST_PENDING = 'GET_POST_PENDING';
